name: Déploiement automatique Fly.io

on:
  push:
    branches:
      - développement

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flyctl
        uses: superfly/flyctl-actions@1.1

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: fly deploy --config fly.toml --app ecoride-old-sun-8183
